<a href="https://colab.research.google.com/github/Argentan/DMA_LAB2/blob/master/tutoriales/03_manejo_de_datos-numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Listas

In [1]:
b = [1, 2, 3]

In [2]:
type(b)

list

Aplicando operadores matemáticos a listas

In [3]:
b + b

[1, 2, 3, 1, 2, 3]

In [4]:
b * 4

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

Solución? For Loops?

In [5]:
for elemento in b:
    print(elemento)

1
2
3


In [6]:
for elemento in b:
    print(elemento + elemento)

2
4
6


In [7]:
for elemento in b:
    print(elemento * 4)

4
8
12


Y si lo quiero guardar en otra variable (por ejemplo 'c = b+b')?

Una forma es:
* definir un array vacío
* recorrer todos los elementos en b
* sumarlos entre sí y meterlos dentro de una lista ([elemento + elemento])
* sumar esta lista a 'c' (**c \+= algo** es lo mismo que **c = c + algo**)

In [8]:
c = []
for elemento in b:
    c += [elemento + elemento]
c

[2, 4, 6]

In [9]:
c = []
for elemento in b:
    c += [elemento * 4]
    print(c)

[4]
[4, 8]
[4, 8, 12]


Alternativa??

# Librería Numpy

Es el paquete de arrays mas comúnmente usado en Python. La diferencia entre un array y una lista nativa es que el array es continuo en memoria mientras que la lista esta encadenada, haciendo que el array sea mucho más rápido de leer y, por tanto, la estructura de datos natural para el procesamiento de grandes cantidades de datos.

In [10]:
import numpy as np

In [11]:
array_normal = [1, 2, 3, 4]

arr1 = np.array([1, 2, 3, 4])
arr1

array([1, 2, 3, 4])

In [12]:
array_normal

[1, 2, 3, 4]

In [13]:
type(array_normal)

list

In [14]:
type(arr1)

numpy.ndarray

In [15]:
arr1.shape

(4,)

Un **ndarray** (n-dimensional array) es un tipo de objeto que representa un arreglo multidimensional de elementos del mismo tipo.

In [16]:
arr1.dtype

dtype('int64')

In [17]:
arr1 + arr1

array([2, 4, 6, 8])

In [18]:
result = arr1 / arr1
result

array([1., 1., 1., 1.])

In [19]:
result.dtype

dtype('float64')

In [20]:
arr1 + 100

array([101, 102, 103, 104])

## Dimensiones

Los arrays de numpy pueden ser unidimensionales (1D), bidimensionales (2D) o cuantas dimensiones se quiera.


In [21]:
data = np.random.rand(3, 5)
data

array([[0.95282521, 0.23872273, 0.21079533, 0.18280218, 0.83703995],
       [0.61456657, 0.19625663, 0.23476351, 0.25651513, 0.72517704],
       [0.57711816, 0.11563746, 0.99213054, 0.5475988 , 0.50187113]])

In [22]:
data = data * 100
data

array([[95.28252147, 23.87227313, 21.07953321, 18.28021793, 83.70399503],
       [61.4566572 , 19.62566293, 23.47635111, 25.65151258, 72.51770436],
       [57.71181621, 11.5637462 , 99.21305432, 54.75987967, 50.18711336]])

In [23]:
data = np.round(data)
data

array([[95., 24., 21., 18., 84.],
       [61., 20., 23., 26., 73.],
       [58., 12., 99., 55., 50.]])

Tamaño de 'data'

In [24]:
data.shape

(3, 5)

## Indexado

El indexado en los ndarray funciona igual que el indexado de listas.

Los elementos de una ndarray se pueden acceder mediante su índice.

* Todos los índices empiezan en 0
* Los índices son números enteros
* El índice máximo es (cantidad de elementos - 1)
* Se accede al elemento con *índice*
* Si el índice es negativo, se cuenta desde el final
* Se puede hacer "slicing" con rangos de índices separados por dos puntos (:)
* Se pueden usar índices negativos que cuentan desde atrás pero empezando en -1

<b>array_name[start : end : step]</b>

start: starting index, inclusive

end: end index, exclusive

step: difference


In [25]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
a[2:5]

array([3, 4, 5])

In [27]:
a[:]

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
a[2:]

array([3, 4, 5, 6, 7])

In [29]:
a[:3]

array([1, 2, 3])

### Para arrays de dos dimensiones

<b>array_name[start : end : step, start : end : step]</b>

start: starting index, inclusive

end: end index, exclusive

step: difference

In [30]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
x.shape

(3, 2)

In [32]:
x[1:, 1]

array([4, 6])

In [33]:
x[:,:]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
y = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [10, 20, 30, 40]])
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 20, 30, 40]])

In [35]:
y.shape

(3, 4)

In [36]:
y[1:, 1:]

array([[ 6,  7,  8],
       [20, 30, 40]])

In [37]:
y[::2, ::2]

array([[ 1,  3],
       [10, 30]])

### Para arrays de tres dimensiones

<b>array_name[start : end : step, start : end : step, start : end : step]</b>

start: starting index, inclusive

end: end index, exclusive

step: difference

In [38]:
z = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 123, 124]]])
z

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[ 13,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22, 123, 124]]])

In [39]:
z.shape

(2, 3, 4)

In [40]:
z[:, :2, :2]

array([[[ 1,  2],
        [ 5,  6]],

       [[13, 14],
        [17, 18]]])

In [41]:
arr1

array([1, 2, 3, 4])

In [42]:
arr1[0]

1

In [43]:
arr1[3]

4

In [44]:
# dará error
# arr1[len(arr1)]

In [45]:
arr1[len(arr1) - 1]

4

In [46]:
arr1[-1]

4

In [47]:
arr2d = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

In [48]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr2d.shape

(3, 3)

In [50]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
arr2d[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
arr2d[1, 1:]

array([5, 6])

In [53]:
arr2d[2, 1:]

array([8, 9])

In [54]:
arr2d[:, 1]

array([2, 5, 8])

## Funciones de agregación

Suelen expresarse como métodos del objeto ndarray. En general, tienen como consecuencia disminuir las dimensiones del arreglo y son muy utilizados en matemáticas y física.<br>
La siguiente tabla muestra los más utilizados, puede encontrar la documentación [aquí](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#calculation).

| Operación | Descripción |
|:----------|:------------|
| `a.sum()`    | Retorna la suma del arreglo en el eje dado |
| `a.min()`    | Retorna el valor mínimo de un eje |
| `a.mean()`   | Retorna la media aritmética en un eje dado |
| `a.var()`    | Retorna la varianza en un eje dado|
| `a.std()`    | Retorna la desviación estándar en un eje dado |
| `a.prod()`   | Retorna el producto en un eje dado |
| `a.argmin()` | Retorna el índice donde ocurren los valores mínimos de cada eje |
| `a.ptp()`    | Valor pico a pico en un eje |
| `a.conj()`   | Retorna el conjugado complejo de todos los elementos |
| `a.round()`  | Retorna el valor redondeado de cada elemento |
| `a.trace()`  | Retorna la suma de las diagonales del arreglo |
| `a.argmax()` | Retorna el índice donde ocurren los valores máximos de cada eje |
| `a.cumsum()` | Retorna la suma acumulativa en un eje dado |
| `a.cumprod()`| Retorna el producto acumulativo en un eje dado |

In [55]:
arr1

array([1, 2, 3, 4])

In [56]:
arr1.mean()

2.5

In [57]:
arr1.std()

1.118033988749895

In [58]:
arr1.shape

(4,)

In [59]:
arr1.size

4

In [60]:
arr2 = np.ones((2, 3))
arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [61]:
arr1.argmax()

3

In [62]:
arr2.shape

(2, 3)

In [63]:
arr2.argmax()

0

In [64]:
arr2.size

6

In [65]:
len(arr2)

2

In [66]:
ceros = np.zeros((10, 2))
ceros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [67]:
len(ceros)

10

In [68]:
ceros.size

20

## Funciones universales

Son funciones optimizadas que operan sobre el array. Difícilmente vamos a necesitar hacer algo que no esté ya implementado. Lista completa de funciones universales: [enlace](https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html#math-operations)

### Funciones para crear ndarrays

Hay muchas formas de crear arreglos en Numpy, puede explorarlas todas en este [enlace](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.array-creation.html). Las más comunes son:

| Función | Descripción |
|:--------|:------------|
| `empty` | Arreglo vacío |
| `zeros` | Arreglo de ceros |
| `ones`  | Arreglo de unos |
| `full`  | Se especifica un valor para llenar todo el arreglo con él |
| `identity` | Unos en la diagonal y cero en el resto |
| `array` | Constructor genérico |
| `fromfunction` | Según una función dada que retorna un valor para cada punto de la coordenada |
| `loadtxt` | Carga los datos de un archivo |

In [69]:
np.ones(3)

array([1., 1., 1.])

In [70]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [71]:
np.full([2,5], fill_value=10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

# Ejercicios

1.   Crear un ndarray de Numpy de 100 números enteros aleatorios con valores de -100 a +100.

NOTA: El método recomendado para generar números aleatorios es mediante el uso de la clase Generator. Ver [Random Generator](https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.Generator)

In [72]:
# Método antiguo (legacy)
arr = np.random.randint(-100, 101, size=100)
arr

array([  23,  -99,   81,   60,  -36,  -39,  -54,   53,   73,   30,   96,
        -66,  -82,   30,   83,   66,    9,   32,   81,  -60,  -37,  -16,
        -77,  -45,   97,  -26,   23,   52,   38,  -69,   33, -100,  -70,
         26,  -36,  -94,  -58,  -17,  -96,   81,   -1,  -51,   42,   48,
         41,  -11,  -54,  -88,   -9,  -17,    7,    7,   12,  -26,  -81,
        -49,   59,   32,   57,   92,  -22,  -90,  -62,   39,   24,   18,
        -49,  -27,  -97,  -89,   64,   93,   21,   -8,   17,   41,  -78,
        -88,   33,   -3,  -53,  -99,   52,   79,  -65,  -69,  -17,   64,
         94,  -74,  -95,   81,   75,  -56,  -64,  -91,   10,   98,   67,
          0])

In [73]:
# Método nuevo (recomendado)
# Crear una instancia de la clase Generator
rng = np.random.default_rng()

# Generar un ndarray de 100 números enteros aleatorios en el rango de -100 a +100
arr = rng.integers(low=-100, high=100, size=100)

print(arr)

[ 13 -56  89  19  72 -27  85  64  86  -9 -78 -51  57 -58 -56 -64  83  86
  38 -14 -87 -17  13  78 -66 -50  56  46 -46  13  43   9  79  92  18 -88
 -45  16  45  86 -81  82  82  98  31 -11 -82  22  85  12 -88  99 -90 -21
 -86  68   0  78  34 -33   4  79 -93  13 -46  50  -6  34  32 -89 -54  84
 -11  22  89  -2 -82 -22  52 -91  17 -27  -8  81 -72 -70  60 -51 -92 -12
  31 -76 -28 -90  54  81 -39  48 -41   6]


2.   Usando arrays de booleanos crear 3 arrays que contengan los positivos, los negativos y los mayores de 50 del array generado en el punto 1.

In [74]:
# Crear arrays booleanos para los números positivos, negativos y mayores de 50
positivos = arr > 0
negativos = arr < 0
mayores_50 = arr > 50

mayores_50

array([False, False,  True, False,  True, False,  True,  True,  True,
       False, False, False,  True, False, False, False,  True,  True,
       False, False, False, False, False,  True, False, False,  True,
       False, False, False, False, False,  True,  True, False, False,
       False, False, False,  True, False,  True,  True,  True, False,
       False, False, False,  True, False, False,  True, False, False,
       False,  True, False,  True, False, False, False,  True, False,
       False, False, False, False, False, False, False, False,  True,
       False, False,  True, False, False, False,  True, False, False,
       False, False,  True, False, False,  True, False, False, False,
       False, False, False, False,  True,  True, False, False, False,
       False])

In [75]:
type(positivos)

numpy.ndarray

In [76]:
positivos.dtype

dtype('bool')

In [77]:
arr

array([ 13, -56,  89,  19,  72, -27,  85,  64,  86,  -9, -78, -51,  57,
       -58, -56, -64,  83,  86,  38, -14, -87, -17,  13,  78, -66, -50,
        56,  46, -46,  13,  43,   9,  79,  92,  18, -88, -45,  16,  45,
        86, -81,  82,  82,  98,  31, -11, -82,  22,  85,  12, -88,  99,
       -90, -21, -86,  68,   0,  78,  34, -33,   4,  79, -93,  13, -46,
        50,  -6,  34,  32, -89, -54,  84, -11,  22,  89,  -2, -82, -22,
        52, -91,  17, -27,  -8,  81, -72, -70,  60, -51, -92, -12,  31,
       -76, -28, -90,  54,  81, -39,  48, -41,   6])

In [78]:
positivos

array([ True, False,  True,  True,  True, False,  True,  True,  True,
       False, False, False,  True, False, False, False,  True,  True,
        True, False, False, False,  True,  True, False, False,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True, False,  True,  True,  True,  True,
       False, False,  True,  True,  True, False,  True, False, False,
       False,  True, False,  True,  True, False,  True,  True, False,
        True, False,  True, False,  True,  True, False, False,  True,
       False,  True,  True, False, False, False,  True, False,  True,
       False, False,  True, False, False,  True, False, False, False,
        True, False, False, False,  True,  True, False,  True, False,
        True])

In [79]:
arr_positivos = arr[positivos]
arr_positivos

array([13, 89, 19, 72, 85, 64, 86, 57, 83, 86, 38, 13, 78, 56, 46, 13, 43,
        9, 79, 92, 18, 16, 45, 86, 82, 82, 98, 31, 22, 85, 12, 99, 68, 78,
       34,  4, 79, 13, 50, 34, 32, 84, 22, 89, 52, 17, 81, 60, 31, 54, 81,
       48,  6])

In [80]:
# Utilizar los arrays booleanos para crear arrays filtrados con los números correspondientes
arr_positivos = arr[positivos]
arr_negativos = arr[negativos]
arr_mayores_50 = arr[mayores_50]

# Imprimir los arrays filtrados
print("Array original:")
print(arr)

print("Positivos:")
print(arr_positivos)

print("Negativos:")
print(arr_negativos)

print("Mayores de 50:")
print(arr_mayores_50)

Array original:
[ 13 -56  89  19  72 -27  85  64  86  -9 -78 -51  57 -58 -56 -64  83  86
  38 -14 -87 -17  13  78 -66 -50  56  46 -46  13  43   9  79  92  18 -88
 -45  16  45  86 -81  82  82  98  31 -11 -82  22  85  12 -88  99 -90 -21
 -86  68   0  78  34 -33   4  79 -93  13 -46  50  -6  34  32 -89 -54  84
 -11  22  89  -2 -82 -22  52 -91  17 -27  -8  81 -72 -70  60 -51 -92 -12
  31 -76 -28 -90  54  81 -39  48 -41   6]
Positivos:
[13 89 19 72 85 64 86 57 83 86 38 13 78 56 46 13 43  9 79 92 18 16 45 86
 82 82 98 31 22 85 12 99 68 78 34  4 79 13 50 34 32 84 22 89 52 17 81 60
 31 54 81 48  6]
Negativos:
[-56 -27  -9 -78 -51 -58 -56 -64 -14 -87 -17 -66 -50 -46 -88 -45 -81 -11
 -82 -88 -90 -21 -86 -33 -93 -46  -6 -89 -54 -11  -2 -82 -22 -91 -27  -8
 -72 -70 -51 -92 -12 -76 -28 -90 -39 -41]
Mayores de 50:
[89 72 85 64 86 57 83 86 78 56 79 92 86 82 82 98 85 99 68 78 79 84 89 52
 81 60 54 81]


3.   Crear un array bidimensional de 5x5 con todos los valores cero. Usando el indexado de arrays, asignar 1 a todos los elementos de la última fila y 5 a todos los elementos de la primera columna. Finalmente, asignar el valor 100 a todos los elementos del subarray central 3x3 de la matriz de 5x5.

In [81]:
# Crear un array bidimensional de 5x5 con valores cero
arr = np.zeros((5, 5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [82]:
# Asignar 1 a todos los elementos de la última fila
arr[-1] = 1
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [83]:
# Asignar 5 a todos los elementos de la primera columna
arr[:, 0] = 5
arr

array([[5., 0., 0., 0., 0.],
       [5., 0., 0., 0., 0.],
       [5., 0., 0., 0., 0.],
       [5., 0., 0., 0., 0.],
       [5., 1., 1., 1., 1.]])

In [84]:
# Asignar 100 a todos los elementos del subarray central 3x3
arr[1:4, 1:4] = 100

# Imprimir el array resultante
print(arr)

[[  5.   0.   0.   0.   0.]
 [  5. 100. 100. 100.   0.]
 [  5. 100. 100. 100.   0.]
 [  5. 100. 100. 100.   0.]
 [  5.   1.   1.   1.   1.]]


4.   Crear una matriz de 10 x 3 con valores aleatorios entre cero y uno



In [85]:
# Crear una matriz de 10x3 con valores aleatorios entre cero y uno
matriz = np.random.rand(10, 3)

print(matriz)

[[0.96519005 0.28592288 0.68870162]
 [0.22833417 0.1080428  0.36081608]
 [0.49806695 0.73692218 0.76456645]
 [0.18051975 0.23158169 0.33990683]
 [0.63719329 0.66289105 0.34981165]
 [0.82960701 0.36969689 0.42572885]
 [0.56290532 0.41533951 0.59406604]
 [0.74456159 0.56056928 0.14173792]
 [0.08956535 0.4843031  0.80074647]
 [0.54130685 0.39265524 0.87609651]]



5.   Buscar el valor mínimo de la matriz creada en el punto 4.

In [86]:
# Buscar el valor mínimo de la matriz
minimo = np.amin(matriz)

print("El valor mínimo de la matriz (np.amin) es:", minimo)

# Otra forma de hacer lo mismo para encontrar el valor mínimo de la matriz
min_value = matriz.min()

print("El valor mínimo de la matriz (np.min) es:", min_value)

El valor mínimo de la matriz (np.amin) es: 0.08956535408314314
El valor mínimo de la matriz (np.min) es: 0.08956535408314314


6.   Buscar la posición (índice) del valor mínimo de la matriz

In [87]:
# Buscar la posición (índice) del valor mínimo de la matriz

indice_minimo_flat = matriz.argmin()
indice_minimo = np.unravel_index(indice_minimo_flat, matriz.shape)

print(f"El valor mínimo es {min_value} y su posición es {indice_minimo}")

print(f'El índice plano del valor mínimo es: {indice_minimo_flat}. El índice en forma de tupla es: {indice_minimo}')

El valor mínimo es 0.08956535408314314 y su posición es (8, 0)
El índice plano del valor mínimo es: 24. El índice en forma de tupla es: (8, 0)
